---
logging:
  level:
    root: WARN
    org.springframework.boot: INFO
    org:
      zalando:
        logbook: TRACE
      springframework:
        # web: DEBUG
        security: DEBUG

spring:
  jpa:
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always
  config:
    activate:
      on-profile: dev

sentry:
  dsn: https://examplePublicKey@o0.ingest.sentry.io/0
  tracesSampleRate: 1.0

logbook:
  strategy: status-at-least
  minimum-status: 400
  format:
    style: http

server:
  address: 0.0.0.0
